config/routes.rb
Rails.application.routes.draw do

  resources :gardens do
    resources :plants, only: [:new, :create]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :plants, only: [:show, :destroy] do
    resources :plant_tags, only: [:new, :create]
  end

  # /plants/:id
end

# NEW
# /plants/new


# As a user I can see one garden's plants
# As a user I can add a plant in a garden
# As a user I can delete a plant

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/garden.rb
class Garden < ApplicationRecord
  has_many :plants, dependent: :destroy

  validates :name, :banner_url, presence: true
end

app/models/plant.rb
class Plant < ApplicationRecord
  belongs_to :garden
  has_many :plant_tags, dependent: :destroy
  has_many :tags, through: :plant_tags

  validates :name, :image_url, presence: true
end

app/models/plant_tag.rb
class PlantTag < ApplicationRecord
  belongs_to :tag
  belongs_to :plant

  validates :tag, uniqueness: { scope: :plant, message: "already added."}
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :plant_tags, dependent: :destroy
  has_many :plants, through: :plant_tags

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/gardens_controller.rb
class GardensController < ApplicationController
  before_action :set_garden, only: [:show, :edit, :update, :destroy]

  # GET /gardens
  def index
    @gardens = Garden.all
  end

  # GET /gardens/1
  def show
  end

  # GET /gardens/new
  def new
    @garden = Garden.new
  end

  # GET /gardens/1/edit
  def edit
  end

  # POST /gardens
  def create
    @garden = Garden.new(garden_params)

    if @garden.save
      redirect_to @garden, notice: 'Garden was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /gardens/1
  def update
    if @garden.update(garden_params)
      redirect_to @garden, notice: 'Garden was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /gardens/1
  def destroy
    @garden.destroy
    redirect_to gardens_url, notice: 'Garden was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_garden
      @garden = Garden.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def garden_params
      params.require(:garden).permit(:name, :banner_url)
    end
end

app/controllers/plant_tags_controller.rb
class PlantTagsController < ApplicationController
  def new
    @plant = Plant.find(params[:plant_id])
    @plant_tag = PlantTag.new
  end

  def create
    @plant = Plant.find(params[:plant_id])
    @tags = Tag.where(id: params[:plant_tag][:tag])

    @tags.each do |tag|
      PlantTag.create(tag: tag, plant: @plant)
    end

    redirect_to garden_path(@plant.garden)
  end
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  def show
    @plant = Plant.find(params[:id])
  end

  def new
    @garden = Garden.find(params[:garden_id])
    @plant = Plant.new
  end

  def create
    @garden = Garden.find(params[:garden_id])

    @plant = Plant.new(plant_params)
    @plant.garden = @garden

    if @plant.save
      redirect_to garden_path(@garden)
    else
      render :new
    end
  end

  def destroy
    @plant = Plant.find(params[:id])
    @plant.destroy

    redirect_to garden_path(@plant.garden)
  end

  private

  def plant_params
    params.require(:plant).permit(:name, :image_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gardens_helper.rb
module GardensHelper
end

app/helpers/plant_tags_helper.rb
module PlantTagsHelper
end

app/helpers/plants_helper.rb
module PlantsHelper
end

app/views/gardens/_form.html.erb
<%= simple_form_for(@garden) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :banner_url %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/gardens/edit.html.erb
<h1>Editing Garden</h1>

<%= render 'form', garden: @garden %>

<%= link_to 'Show', @garden %> |
<%= link_to 'Back', gardens_path %>

app/views/gardens/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Gardens</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Banner url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @gardens.each do |garden| %>
      <tr>
        <td><%= garden.name %></td>
        <td><%= garden.banner_url %></td>
        <td><%= link_to 'Show', garden %></td>
        <td><%= link_to 'Edit', edit_garden_path(garden) %></td>
        <td><%= link_to 'Destroy', garden, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Garden', new_garden_path %>

app/views/gardens/new.html.erb
<h1>New Garden</h1>

<%= render 'form', garden: @garden %>

<%= link_to 'Back', gardens_path %>

app/views/gardens/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('<%= @garden.banner_url %>');">
  <h1><%= @garden.name %></h1>
</div>
<div class="container mt-3 text-center">
  <div class="row">
    <% @garden.plants.each do |plant| %>
      <div class="col-4">
        <div class="plant-card" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('<%= plant.image_url %>');">
          <h4><%= link_to plant.name, plant_path(plant)  %></h4>

          <%= link_to "X", plant_path(plant), class: "card-action plant-destroy", method: :delete, data: { confirm: "Are you sure?"} %>
          <%= link_to "+", new_plant_plant_tag_path(plant), class: "add-tag card-action" %>

          <div class="card-tags">
            <% plant.tags.each do |tag| %>
              <span><%= tag.name %></span>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <%= link_to "Add Plant", new_garden_plant_path(@garden) %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ParksAndPlants</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/plant_tags/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-6 offset-3">
      <h2 class="text-center">Add plant</h2>
      <%= simple_form_for [@plant, @plant_tag ] do |f| %>
        <%= f.input :tag, collection: Tag.all, input_html: { multiple: true, include_hidden: false } %>
        <%= f.submit "Associate Tag", class: 'btn btn-primary' %>
      <% end %>

    </div>
  </div>
</div>

app/views/plants/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-6 offset-3">
      <h2 class="text-center">Add plant</h2>
      <%= simple_form_for [@garden, @plant] do |f| %>
        <%= f.input :name %>
        <%= f.input :image_url %>
        <%= f.submit "Create Plant", class: 'btn btn-primary' %>
      <% end %>

    </div>
  </div>
</div>

app/views/plants/show.html.erb
<div class="container">
  <h1><%= @plant.name %></h1>

</div>